/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Serialisasi;
import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author FATHUR
 */
public class MainBook extends javax.swing.JFrame {
    public static Book Book;
    private final String path;

    /**
     * Creates new form MainBook
     */
    public MainBook() {
        initComponents();
        
        Book = new Book();
        path = System.getProperty("user.dir") + File.separator
        + "Book.ser";
    }
    private void lihatHasilSerialization(){
        FileReader filereader;
        BufferedReader bufferedreader;
        StringBuilder stringbuilder = new StringBuilder();
        
        try {
            File file = new File(path);
            filereader = new FileReader(file);
            bufferedreader = new BufferedReader(filereader);
            String line;
            while ((line = bufferedreader.readLine()) !=null){
                stringbuilder.append(line).append("\r\n");
            }
            bufferedreader.close();
            filereader.close();
            
        } catch (Exception e) {
        }
        serialisasi.setText(stringbuilder.toString());
            
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEntry = new javax.swing.JButton();
        btnSerialisasi = new javax.swing.JButton();
        btnDiserialisasi = new javax.swing.JButton();
        split = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        serialisasi = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        diserialisasi = new javax.swing.JTextArea();
        jComboBox = new javax.swing.JComboBox<>();
        jCombo2 = new javax.swing.JComboBox<>();
        jCombo3 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEntry.setText("Entry Data ");
        btnEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntryActionPerformed(evt);
            }
        });

        btnSerialisasi.setText("Serialisasi");
        btnSerialisasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSerialisasiActionPerformed(evt);
            }
        });

        btnDiserialisasi.setText("Diserialisasi");
        btnDiserialisasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiserialisasiActionPerformed(evt);
            }
        });

        split.setDividerLocation(150);
        split.setDividerSize(10);
        split.setOneTouchExpandable(true);

        serialisasi.setColumns(20);
        serialisasi.setRows(5);
        jScrollPane1.setViewportView(serialisasi);

        split.setLeftComponent(jScrollPane1);

        diserialisasi.setColumns(20);
        diserialisasi.setRows(5);
        jScrollPane2.setViewportView(diserialisasi);

        split.setRightComponent(jScrollPane2);

        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Merah", "Hijau", "Hitam" }));
        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });

        jCombo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arial", "Vendana", "Default", " " }));
        jCombo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombo2ActionPerformed(evt);
            }
        });

        jCombo3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "14", "16" }));
        jCombo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombo3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(split, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSerialisasi, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDiserialisasi, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCombo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSerialisasi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDiserialisasi, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCombo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(split, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntryActionPerformed
        // TODO add your handling code here:
        AddBook tambah = new AddBook(this,true);
        tambah.setVisible(true);
    }//GEN-LAST:event_btnEntryActionPerformed

    private void btnSerialisasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSerialisasiActionPerformed
        // TODO add your handling code here:
        FileOutputStream fos;
        ObjectOutputStream oos;
        try {
            fos = new FileOutputStream(new File(path));
            oos = new ObjectOutputStream(fos);
            oos.writeObject(Book);
            oos.close();
            fos.close();
            
            lihatHasilSerialization();
        } catch (FileNotFoundException e){ 
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnSerialisasiActionPerformed

    private void btnDiserialisasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiserialisasiActionPerformed
        // TODO add your handling code here:
        FileInputStream fis;
        ObjectInputStream ois;
        try {
            fis = new FileInputStream(new File(path));
            ois = new ObjectInputStream(fis);
            ois.close();
            fis.close();
        } catch (FileNotFoundException e){
        } catch (IOException  ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnDiserialisasiActionPerformed

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed
        // TODO add your handling code here:
        String selectedColor = (String) jComboBox.getSelectedItem();
        Color color = Color.BLACK;

switch (selectedColor) {
    case "merah":
        color = Color.RED;
        break;
    case "hijau":
        color = Color.GREEN;
        break;
    case "Hitam":
        color = Color.BLACK;
        break;
    default:
        color = Color.BLACK;
}



// Implementasi untuk JTextArea (areaSerialization dan areaDeserialization)
serialisasi.setForeground(color);
diserialisasi.setForeground(color);

    }//GEN-LAST:event_jComboBoxActionPerformed

    private void jCombo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombo2ActionPerformed
        // TODO add your handling code here: 
        if(jCombo2.getSelectedItem()=="Arial") {
            serialisasi.setFont(new Font ("Arial", Font.PLAIN,12));
            diserialisasi.setFont(new Font ("Arial", Font.PLAIN,12));
        } else if (jCombo2.getSelectedItem()=="Verdana"){
            serialisasi.setFont(new Font ("Verdana", Font.PLAIN,12));
            diserialisasi.setFont(new Font ("Verdana", Font.PLAIN,12));
        } else {
            serialisasi.setFont(new Font ("Default", Font.PLAIN,12));
            diserialisasi.setFont(new Font ("Default", Font.PLAIN,12));
        }
    }//GEN-LAST:event_jCombo2ActionPerformed

    private void jCombo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombo3ActionPerformed
        // TODO add your handling code here:
        if(jCombo2.getSelectedItem()=="12") {
            serialisasi.setFont(new Font (serialisasi.getFont().getName(),serialisasi.getFont().getStyle(),12));
            diserialisasi.setFont(new Font (diserialisasi.getFont().getName(),diserialisasi.getFont().getStyle(),12));
        } else if (jCombo2.getSelectedItem()=="14"){
            serialisasi.setFont(new Font (serialisasi.getFont().getName(),serialisasi.getFont().getStyle(),14));
            diserialisasi.setFont(new Font (diserialisasi.getFont().getName(),diserialisasi.getFont().getStyle(),14));
        } else {
            serialisasi.setFont(new Font (serialisasi.getFont().getName(),serialisasi.getFont().getStyle(),16));
            diserialisasi.setFont(new Font (diserialisasi.getFont().getName(),diserialisasi.getFont().getStyle(),16));
        }
    }//GEN-LAST:event_jCombo3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDiserialisasi;
    private javax.swing.JButton btnEntry;
    private javax.swing.JButton btnSerialisasi;
    private javax.swing.JTextArea diserialisasi;
    private javax.swing.JComboBox<String> jCombo2;
    private javax.swing.JComboBox<String> jCombo3;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea serialisasi;
    private javax.swing.JSplitPane split;
    // End of variables declaration//GEN-END:variables
}
